version: '3.3'

services:

  db:
    image: postgres:13
    volumes:
      - ./schema_design/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  service:
    build: ./django_api
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    depends_on:
      - service
    ports:
      - '80:80'

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/openapi.yaml:/swagger.yaml 
    environment:
      SWAGGER_JSON: /swagger.yaml
    depends_on:
      - nginx
    ports:
      - "8082:8080"
    

volumes:
  postgres_data:
  static_value:
  media_value: